### 추천 시스템 만들기

1. #### 웹공간으로부터 텍스트를 수집한다. (웹스크래핑/크롤링)
   - 크롤링 도구 : selenium
   - 텍스트 구조화 : BeautifulSoup
   - 데이터 증식(권장 X) : 텍스트 데이터가 부족하기 때문에 동일한 데이터를 늘린다.
   - 위키피디아, 북스코퍼스(저작권이 풀린 도서), 등

2. #### 데이터 전처리
   - 전처리 방법

    토큰화, 텍스트 정제, 단어 정처리, 인코딩, 패딩, One-Hot Encoding

3. #### 언어 모델링
   - 알고리즘 선택하기 (ML, DL, DM - Data Mining)

     각 상황에 맞게 알고리즘을 구상한다.

### n-gram - 전통적 통계 기반 언어 모델

n : 숫자

이 알고리즘을 통해 **문장** 및 **문단**간의 **유사도**를 처리한다.
</br>
</br>

---

예시: "오늘 점심 추천 메뉴 : 소고기볶음밥, 김치볶음밥"

유니그램(n=1) : 한 단어씩 나눈 것

(오늘, 점심, 추천, 메뉴, 소고기볶음밥, 햄볶음밥)

바이그램(n=2) : 두 단어씩 나눈 것

(오늘 점심, 점심 추천, 추천 메뉴, 메뉴 소고기볶음밥, 소고기볶음밥 햄볶음밥)
</br>
</br>

---


[확률 구하기]

1. P(소고기볶음밥|점심 추천 메뉴)

 = count(점심 추천 메뉴 소고기볶음밥) /count(점심 추천 메뉴)

 = 20/30

2. P(햄볶음밥|점심 추천 메뉴)

 = count(점심 추천 메뉴 햄볶음밥) /count(점심 추천 메뉴)

 = 5/30

- count(점심 추천 메뉴) : 전체 문서에서 점심 다음 추천, 추천 다음 메뉴가 나온 횟수
</br>
</br>
---

[결론]

점심 추천 메뉴 ? (소고기볶음밥)

*내가 이전에 검색했던 기록을 통해서 확률을 구하고 그 확률을 통해서 기록을 알려준다.

#### 주의사항

한국어는 단어의 순서가 큰 의미가 없다.

나는 지금 자연어 공부해요 = 자연어 공부해요 나는 지금
</br>
</br>
→ 신경망(RNN, LSTM) 기반

Linear Regression (예측, 회귀) ; wx+b

→ Logistic Regression (이진분류, Sigmoid Function) ; 범위 (0, 1)

→ SOFTMAX (이진분류가 여러 개 있으면 **다중분류**가 된다.)

→ 얕은 신경망 : Neural Network (입력층, 출력층 존)    

h(x) = wx + b

sigmoid(h(x)) = 1 / (1 + e^-(h(x)))
</br>
</br>
깊은 신경망 : DNN, CNN, RNN


#### One Hot Enconding, DTM(Document Term Matrix, TF), TDM, TFIDF(TF*IDF)
</br>
Document : 실제 문서, 소설, 등

DTM을 Transpose 한 것 : TDM

행에 Term을 사용하면, 보기가 어렵기 때문에 DTM을 주로 사용한다.
</br>
</br>

[행렬식 모습]

......... 단어1   단어2 ..... 단어m

문서1      5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M차원 벡터 공간(5, 0, ....1)

문서2

.....

문서n
</br>
</br>
[행렬식 분석]
- 행단위로 최대값을 찾는다는 의미는 "빈도수가 가장 많이 나온 단어를 찾겠다는 의미이다.


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
#CountVectorizer : 단어의 빈도수로 벡터 생성

In [ ]:
#리스트 안에 문자열이 1개 존재한다.
corpus = ['나는 지금 자연어 처리를 공부해요. 나는 자연어 좋아요.']
vector = CountVectorizer()

In [ ]:
#fit: 각각의 단어에 인덱스 부여 (0~5번까지 부여)
#transform : corpus에 저장된 문장을 fit 결과에 맞게 변환(빈도수)한다.
vector.fit_transform(corpus)

<1x6 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

Sparse Matrix(희소행렬(1x6)) : 행렬 요소값이 대부분 0인 행렬

단점: 공간낭비, 연산량

In [ ]:
vector.fit_transform(corpus).toarray()

array([[1, 2, 2, 1, 1, 1]])

In [ ]:
vector.vocabulary_

{'나는': 1, '지금': 4, '자연어': 2, '처리를': 5, '공부해요': 0, '좋아요': 3}

### DTM

행에 문서가 오고, 열에는 단어의 빈도수가 온다.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [ ]:
corpus = [
    'I love you', #문서 1
    'I can do it love', #문서 2
    'I want your love' #문서 3
]

In [ ]:
v = CountVectorizer() #객체생성

In [ ]:
v.fit_transform(corpus).toarray()

array([[0, 0, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 1]])

In [ ]:
v.vocabulary_ #'I'라는 단어가 빠진 이유는? - 내부적으로 길이가 1인 단어가 빠졌기 때문이다. (default)

{'love': 3, 'you': 5, 'can': 0, 'do': 1, 'it': 2, 'want': 4, 'your': 6}

In [ ]:
tfv = TfidfVectorizer() #객체생성

#### tf * idf

TFIDF

tf(d, t) : 문서에서 단어의 등장 횟수
(단어가 여러 번 발생할수록 값이 증가한다.)

idf(d, t) : 단어가 흔하게 문서에 등장할 수록 값이 감소하며, 단어가 여러 번 발생하지 않을 때는 증가한다.

<!-- tf - idf → 비례관계

- tf가 클 수록 idf도 크다
  = 단어 빈도수가 높다 -->

- df(t)가 크면, 단어가 흔하게 문서에 등장한다.

즉, 문서당 빈도수가 적고 흔하지 않은 단어들을 추출하기 위해 사용한다.

In [ ]:
#{'love': 3, 'you': 5, 'can': 0, 'do': 1, 'it': 2, 'want': 4, 'your': 6}
# can do it은 다른 문서에서 볼 수 없는 단어이기 때문에 값이 크게 나온다.
tfv.fit_transform(corpus).toarray()

array([[0.        , 0.        , 0.        , 0.50854232, 0.        ,
        0.861037  , 0.        ],
       [0.54645401, 0.54645401, 0.54645401, 0.32274454, 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.38537163, 0.65249088,
        0.        , 0.65249088]])

In [ ]:
import numpy as np
from numpy import dot
from numpy.linalg import norm #선형함수들이 정의되어 있다.

In [ ]:
#document 각 열은 영화 대사에 등장한 단어(사랑, 돈, 운명, 증오)의 빈도
document1 = np.array([1, 1, 1, 0])
document2 = np.array([0, 1, 1, 1])
document3 = np.array([0, 5, 5, 5])

#### document 사이 유클리디안 거리 구하기

d2를 기준으로 했을 경우,
유클리디안 거리는 document1 + documnet2 > document2 + document3 이기 때문에
document1과 document2의 유사도가 더 크다.

#### cosine 유사도 구하기

In [ ]:
#cosine 유사도 구하기 (documnet1과 document2 사이의 유사도)
dot(document1, document2) / (norm(document1)*norm(document2))

0.6666666666666667

In [ ]:
#cosine 유사도 구하기 (documnet2과 document3 사이의 유사도)
dot(document2, document3) / (norm(document2)*norm(document3))

1.0

In [ ]:
#cosine 유사도 구하기 (documnet1과 document3 사이의 유사도)
dot(document1, document3) / (norm(document1)*norm(document3))

0.6666666666666666

#### 자카드 유사도

자카드 유사도(d1, d2) = (d1 교집합 d2) / (d1 합집합 d2)
</br></br>
자카드 유사도가 1인 경우?

d1 교집합 d2 = d1 합집합 d2

→ d1, d2가 동일하다.


*pandas 연습 많이 하기

**[코사인유사도 기반 와인 추천시스템 개발]**

- 제공받은 csv 파일 로드
- 상위 5,000개의 와인 데이터만 추출하여 변수에 저장
- description 열 추출
- 불용어 제거 (길이가 짧은 단어, 불용어 사전에 등록된 단어, 5,000개 문서 중 단어 빈도 수가 3개 이하인 경우 제거, 등)
- DTM 구성 (if 시간이 많이 소요되면, 상위 1,000개로 구성한다.)
- TF-IDF 행렬 구성 (Matrix Shape : 5,000 * 단어 개수)
- 코사인 유사도 (Matrix Shape : 5,000 * 5,000)
</br>
예시) Problem : 번호가 50번에 해당되는 와인과 가장 유사한 와인을 추천해줘
Answer : 가장 유사한 와인 10개 추천
- 대부분 cosine 유사도가 0일텐데, 여기서 유사도가 가장 최댓값인 10개의 와인 추출하기


#### movies 추천 알고리즘 개발

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
#데이터 읽어오기
df = pd.read_csv("/content/movies_metadata.csv")
df

<ipython-input-39-6f676e52c8ef>:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/movies_metadata.csv")


adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1      False                                                NaN  65000000   
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3      False                                                NaN  16000000   
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
...      ...                                                ...       ...   
45461  False                                                NaN         0   
45462  False                                                NaN         0   
45463  False                                                NaN         0   
45464  False                                                NaN         0   
45465  False                                                NaN         0   

                                                  genres  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                         [{'id': 35, 'name': 'Comedy'}]   
...                                                  ...   
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...   
45462                      [{'id': 18, 'name': 'Drama'}]   
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...   
45464                                                 []   
45465                                                 []   

                                   homepage      id    imdb_id  \
0      http://toystory.disney.com/toy-story     862  tt0114709   
1                                       NaN    8844  tt0113497   
2                                       NaN   15602  tt0113228   
3                                       NaN   31357  tt0114885   
4                                       NaN   11862  tt0113041   
...                                     ...     ...        ...   
45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470   
45462                                   NaN  111109  tt2028550   
45463                                   NaN   67758  tt0303758   
45464                                   NaN  227506  tt0008536   
45465                                   NaN  461257  tt6980792   

      original_language               original_title  \
0                    en                    Toy Story   
1                    en                      Jumanji   
2                    en             Grumpier Old Men   
3                    en            Waiting to Exhale   
4                    en  Father of the Bride Part II   
...                 ...                          ...   
45461                fa                      رگ خواب   
45462                tl          Siglo ng Pagluluwal   
45463                en                     Betrayal   
45464                en          Satana likuyushchiy   
45465                en                     Queerama   

                                                overview  ... release_date  \
0      Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1      When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2      A family wedding reignites the ancient feud be...  ...   1995-12-22   
3      Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4      Just when George Banks has recovered from his ...  ...   1995-02-10   
...                                                  ...  ...          ...   
45461        Rising and falling between a man and woman.  ...          NaN   
45462  An artist struggles to finish his work while a...  ...   2011-11-17   
45463  When one of her hits goes wrong, a professiona...  ...   2003-08-01   
45464  In a small town live two brothers, one a minis...  ...   1917-10-21   
45465  50 years after decriminalisati

In [ ]:
#1,000개 뽑아오기
df = df.head(10000)

In [ ]:
df

adult                              belongs_to_collection    budget  \
0     False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1     False                                                NaN  65000000   
2     False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3     False                                                NaN  16000000   
4     False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
...     ...                                                ...       ...   
9995  False                                                NaN         0   
9996  False                                                NaN   4500000   
9997  False                                                NaN   9200000   
9998  False                                                NaN         0   
9999  False  {'id': 124879, 'name': 'State Property Collect...         0   

                                                 genres  \
0     [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2     [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                        [{'id': 35, 'name': 'Comedy'}]   
...                                                 ...   
9995  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...   
9996                      [{'id': 18, 'name': 'Drama'}]   
9997  [{'id': 37, 'name': 'Western'}, {'id': 35, 'na...   
9998  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...   
9999  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   

                                  homepage     id    imdb_id  \
0     http://toystory.disney.com/toy-story    862  tt0114709   
1                                      NaN   8844  tt0113497   
2                                      NaN  15602  tt0113228   
3                                      NaN  31357  tt0114885   
4                                      NaN  11862  tt0113041   
...                                    ...    ...        ...   
9995                                   NaN  43379  tt0043809   
9996                                   NaN   9393  tt0384369   
9997                                   NaN  16972  tt0079180   
9998                                   NaN  21325  tt0355857   
9999                                   NaN  13409  tt0403537   

     original_language                 original_title  \
0                   en                      Toy Story   
1                   en                        Jumanji   
2                   en               Grumpier Old Men   
3                   en              Waiting to Exhale   
4                   en    Father of the Bride Part II   
...                ...                            ...   
9995                it              Miracolo a Milano   
9996                de  Napola – Elite für den Führer   
9997                en                 The Frisco Kid   
9998                ja                        Onmyoji   
9999                en               State Property 2   

                                               overview  ... release_date  \
0     Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1     When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2     A family wedding reignites the ancient feud be...  ...   1995-12-22   
3     Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4     Just when George Banks has recovered from his ...  ...   1995-02-10   
...                                                 ...  ...          ...   
9995  Once upon a time an old woman discovers a baby...  ...   1951-02-08   
9996  In 1942, Friedrich Weimer's boxing skills get ...  ...   2004-07-04   
9997  Rabbi Avram arrives in Philadelphia from Polan...  ...   1979-07-06   
9998  During a dark time in the Heian period, when e...  ...   2001-10-06   
9999  Three gangsters vie for control of the streets...  ...   2005-04-13   

     

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  10000 non-null  object 
 1   belongs_to_collection  1421 non-null   object 
 2   budget                 10000 non-null  object 
 3   genres                 10000 non-null  object 
 4   homepage               662 non-null    object 
 5   id                     10000 non-null  object 
 6   imdb_id                9999 non-null   object 
 7   original_language      10000 non-null  object 
 8   original_title         10000 non-null  object 
 9   overview               9971 non-null   object 
 10  popularity             10000 non-null  object 
 11  poster_path            9969 non-null   object 
 12  production_companies   10000 non-null  object 
 13  production_countries   10000 non-null  object 
 14  release_date           9995 non-null   object 
 15  rev

In [ ]:
df.isnull().sum(axis = 0) #결측값 개수가 나온다.
#belongs_to_collection, homepage, overview, poster_path, tagline에 결측값 존재
#하지만, 우리는 overview만 사용할 것이기 때문에 이 29개의 결측값만 바꿔줘야한다.
# (의미없는 계산값으로 변경)

adult                       0
belongs_to_collection    8579
budget                      0
genres                      0
homepage                 9338
id                          0
imdb_id                     1
original_language           0
original_title              0
overview                   29
popularity                  0
poster_path                31
production_companies        0
production_countries        0
release_date                5
revenue                     0
runtime                     6
spoken_languages            0
status                      8
tagline                  3108
title                       0
video                       0
vote_average                0
vote_count                  0
dtype: int64

In [ ]:
df['overview'] = df['overview'].fillna('') #fillna로 null 값 채워주기

<ipython-input-47-bed5296cde05>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['overview'] = df['overview'].fillna('') #fillna로 null 값 채워주기


In [ ]:
df['overview'].isnull().sum(axis = 0) #결측값 0을 확인해준다.

0

In [ ]:
#불용어 제거
tfidf = TfidfVectorizer(stop_words = 'english')

In [ ]:
tfidf_m = tfidf.fit_transform(df['overview'])
tfidf_m.shape
#단어 32,350개, overview 10,000개

(10000, 32350)

In [ ]:
tfidf_m #3억개의 요소 .. (영화끼리 유사도)

<10000x32350 sparse matrix of type '<class 'numpy.float64'>'
	with 268918 stored elements in Compressed Sparse Row format>

In [ ]:
#코사인 유사도
cos_sim = cosine_similarity(tfidf_m, tfidf_m)

In [ ]:
cos_sim.shape

(10000, 10000)

In [ ]:
cos_sim[0] #첫번째 영화와 다른 영화들의 코사인 유사도

array([1.        , 0.01682915, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [ ]:
df['title']
df.index

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
df['title'] #고유의 인덱스(절대번호) 접근 - iloc (특정 행과 열에 접근)

0                          Toy Story
1                            Jumanji
2                   Grumpier Old Men
3                  Waiting to Exhale
4        Father of the Bride Part II
                    ...             
9995                Miracle in Milan
9996                 Before the Fall
9997                  The Frisco Kid
9998    Onmyoji: The Yin Yang Master
9999                State Property 2
Name: title, Length: 10000, dtype: object

In [ ]:
data = dict(zip(df['title'], df.index)) #인덱스와 영화 제목을 딕셔너리 형태로 생성
i = data['Toy Story']
print(i)

0


In [ ]:
data

{'Toy Story': 0,
 'Jumanji': 1,
 'Grumpier Old Men': 2,
 'Waiting to Exhale': 3,
 'Father of the Bride Part II': 4,
 'Heat': 5,
 'Sabrina': 888,
 'Tom and Huck': 7,
 'Sudden Death': 8,
 'GoldenEye': 9,
 'The American President': 10,
 'Dracula: Dead and Loving It': 11,
 'Balto': 12,
 'Nixon': 13,
 'Cutthroat Island': 14,
 'Casino': 15,
 'Sense and Sensibility': 16,
 'Four Rooms': 17,
 'Ace Ventura: When Nature Calls': 18,
 'Money Train': 19,
 'Get Shorty': 20,
 'Copycat': 21,
 'Assassins': 22,
 'Powder': 23,
 'Leaving Las Vegas': 24,
 'Othello': 2733,
 'Now and Then': 26,
 'Persuasion': 27,
 'The City of Lost Children': 28,
 'Shanghai Triad': 29,
 'Dangerous Minds': 30,
 'Twelve Monkeys': 31,
 'Wings of Courage': 32,
 'Babe': 33,
 'Carrington': 34,
 'Dead Man Walking': 35,
 'Across the Sea of Time': 36,
 'It Takes Two': 37,
 'Clueless': 38,
 'Cry, the Beloved Country': 39,
 'Richard III': 7185,
 'Dead Presidents': 41,
 'Restoration': 42,
 'Mortal Kombat': 43,
 'To Die For': 44,
 'How To

In [1]:
def recommend(t, cosine_sim = cos_sim): #t에는 제목 전달
  idx = data[t] #딕셔너리 키 전달 - value(인덱스 추출)
  #idx 해당하는 cosine 유사도를 가져온다.
  #print(cosine_sim[idx])
  sim_scores = list(enumerate(cosine_sim[idx])) #인덱스번호와 유사도를 같이 내보내기 위해 열거형 사용
  print(sim_scores)
  ss = sorted(sim_scores, key = lambda x:x[1], reverse = True) #내림차순 정렬
  #print(ss)
  ss_scores = ss[1:11] #1~10등까지 출력
  res = [i[0]  for i in ss_scores]
  return df['title'].iloc[res] #영화제목 출력을 하기 위해서 iloc를 넣는다?? [iloc 찾아보자..]

NameError: ignored

In [ ]:
recommend('Toy Story')

2997                                    Toy Story 2
8327                                      The Champ
1071                          Rebel Without a Cause
3057                                Man on the Moon
1932                                      Condorman
485                                          Malice
5797                                  Class of 1984
7254                                 Africa Screams
6944                               Rivers and Tides
7615    The First $20 Million Is Always the Hardest
Name: title, dtype: object